version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all-go-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all-github-action-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '@iot-app-kit/*'
      - dependency-name: '@aws-sdk/*'
      - dependency-name: '@cloudscape-design/*'
    groups:
      all-node-dependencies:
        patterns:
          - '*'
