version: '3.0'

services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-8.4.0}
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      start_period: 30s
      start_interval: 500ms
    volumes:
      - ~/.aws:/usr/share/grafana/.aws
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
