// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');
const path = require('path');

const custom = standard.jestConfig();

// Refer to https://github.com/grafana/grafana/blame/8949e574e6288671343b80991479e2e2b9adfc88/packages/grafana-toolkit/src/config/jest.plugin.config.ts#L85
custom.transform = {
  '^.+\\.(js|jsx|mjs)$': [
    require.resolve('babel-jest'),
    { configFile: path.resolve(__dirname, './jest.babel.config.js') },
  ],
  '^.+\\.tsx?$': require.resolve('ts-jest'),
},

custom.moduleNameMapper['\\.(hdr)$'] = '<rootDir>/tests/utils/__mocks__/styleMock.js';

module.exports = custom;
