/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in .config/README.md
 */

/*
 * This utility function is useful in combination with jest `transformIgnorePatterns` config
 * to transform specific packages (e.g.ES modules) in a projects node_modules folder.
 */
const nodeModulesToTransform = (moduleNames) => `node_modules\/(?!(${moduleNames.join('|')})\/)`;

// Array of known nested grafana package dependencies that only bundle an ESM version
const grafanaESModules = [
  '@cloudscape-design',
  '@popperjs',
  '@react-dnd',
  'd3',
  'd3-array',
  'd3-color',
  'd3-force',
  'd3-format',
  'd3-interpolate',
  'd3-scale-chromatic',
  'dnd-core',
  'internmap',
  'ol',
  'react-colorful',
  'react-cytoscapejs',
  'react-dnd',
  'react-dnd-html5-backend',
  'uuid',
];

module.exports = {
  nodeModulesToTransform,
  grafanaESModules,
};
